"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os 
import dj_database_url # Pour la connexion à PostgreSQL sur Render

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La clé secrète est lue depuis une variable d'environnement (SECRET_KEY)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-n0%=v415&v9$%=l1ik+o$nx)xqh06$vlx#b49wq-_m(tzwa_t=')

# SECURITY WARNING: don't run with debug turned on in production!
# CONSERVÉ: DEBUG = False pour la production
DEBUG = False

# CONSERVÉ: Utilisé pour la première phase de déploiement. À remplacer par l'URL Render après.
ALLOWED_HOSTS = ["*"] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuration de la base de données pour Render (PostgreSQL)
if not DEBUG:
    # Utilise la variable d'environnement DATABASE_URL fournie par Render
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    # Utilise SQLite3 localement
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT où les fichiers seront collectés pour la production
STATIC_ROOT = BASE_DIR / "staticfiles"
#Les répertoires de vos fichiers statiques locaux
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# EMAIL/SMTP CONFIGURATION (SendGrid - Sécurisé)
# ==============================================================================

# Spécifie l'utilisation du backend SMTP de Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Hôte SMTP de SendGrid
EMAIL_HOST = 'smtp.sendgrid.net' 

# Port SMTP (587 pour TLS)
EMAIL_PORT = 587 

# la sécurité TLS
EMAIL_USE_TLS = True 

# Le nom d'utilisateur standard de SendGrid
EMAIL_HOST_USER = 'apikey' 

#  La clé API est lue depuis la variable d'environnement sur Render
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY') 

# Adresse par défaut de l'expéditeur (Doit être une adresse VÉRIFIÉE sur SendGrid)
DEFAULT_FROM_EMAIL = 'orpheengouessi0810@gmail.com' 

# Adresse e-mail du destinataire 
RECIPIENT_EMAIL = 'orpheengouessi0810@gmail.com'